server:
  port: 8070

spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/places
    username: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
---

spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://pg-docker:5432/places